AWSTemplateFormatVersion: "2010-09-09"
Description: "Cloudy Sky Cfn 01"

Resources:

  DeploymentBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

Outputs:
  OutputDeploymentBucketArn:
    Value: !GetAtt DeploymentBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DeploymentBucketArn"
  OutputDeploymentBucketName:
    Value: !Ref DeploymentBucket
    Export:
      Name: !Sub "${AWS::StackName}-DeploymentBucketName"
