name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      stack-name:
        type: string
        default: CloudySky
      region:
        type: string
        default: ap-southeast-1

jobs:
  provision:
    runs-on: ubuntu-latest
    environment: PersonalDev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      AWS_REGION: ${{ inputs.region }}
    steps:
      - name: WhichCheck
        run: which aws
      - name: AwsHelpCheck
        run: aws --help
      - name: ListCheck
        run: aws cloudformation list-stacks
      - name: Checkout self
        uses: actions/checkout@v3
      - name: Create-update Stack
        shell: bash
        run: |
          aws cloudformation create-stack --stack-name ${{ inputs.stack-name }} --template-body '$(cat ./resources/cfn/cloudy.yml)'
