name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      stack-name:
        type: string
        default: CloudySky

jobs:
  provision:
    runs-on: ubuntu-latest
    environment: PersonalDev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
    steps:
      - name: ListCheck
        run: aws cloudformation list-stacks
      - name: Checkout self
        uses: actions/checkout@v3
      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::111111111111:role/my-github-actions-role-test
          aws-region: eu-west-2
