name: Build and deploy
on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        default: ap-southeast-1

jobs:
  provision:
    runs-on: ubuntu-latest
    environment: PersonalDev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      AWS_REGION: ${{ inputs.region }}
    steps:
      - name: Compile all code
        run: echo "::warning title:Not got any code to compile!"
      - name: Provision cloudy01
        run: aws cloudformation deploy --stack-name CloudyO1 --template-file $GITHUB_WORKSPACE/resources/cfn/cloudy01.yml --capabilities CAPABILITY_IAM
      - name: Provision cloudy02
        run: aws cloudformation deploy --stack-name Cloudy02 --template-file $GITHUB_WORKSPACE/resources/cfn/cloudy02.yml --capabilities CAPABILITY_IAM


